version: '3.8'

services:
  
  # Prometheus for monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml # Prometheus config file
      - prometheus_storage:/prometheus # Persistent storage for Prometheus data
    ports:
      - "9090:9090"
    networks:
      - monitoring_network

  # Grafana for visualizing monitoring data
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER} # Reference .env variable for Grafana admin user
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD} # Reference .env variable for Grafana admin password
    volumes:
      - grafana_storage:/var/lib/grafana # Persistent storage for Grafana dashboards and configs
    ports:
      - "4001:3000" # Expose Grafana UI on external port 4001
    depends_on:
      - prometheus
    networks:
      - monitoring_network

networks:
  monitoring_network:
    driver: bridge

volumes:
  prometheus_storage:
    driver: local
  grafana_storage:
    driver: local
